import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org" target="blank">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Distinctio voluptatem expedita eaque numquam soluta ab voluptatibus, assumenda temporibus autem, inventore, ipsam reprehenderit aperiam sapiente qui enim rerum molestias minima odio.
        </p>
      </main>
    </>
  )
};

export default Home;